### PR TITLE
Added some links and edited the README.md file

### PR DESCRIPTION
**Pull request by Jainan-Tandel**

### CODE REVIEW

**Comment by mastrolinux** [comment]
There are some conflicts, please fix them and I will merge

**Comment by sbhklr** [comment]
It's been open for a while and the merge conflict was basically just one character so I resolved it.

**Comment by kittaakos** [comment]
@mastrolinux, can you look into the updated PR? The conflict has been resolved. Thank you!

**Comment by mastrolinux** [comment]
LGTM

**Comment by kittaakos** [comment]
Thank you all for the update! 🙏

**Pull request merged**
